name = "gleesend"
description = "A resend library for the Gleam programming language"
version = "2.0.2"
licences = ["MIT"]
repository = { type = "github", user = "dinkelspiel", repo = "gleesend" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_hackney = ">= 1.2.0 and < 2.0.0"
